refactor: change references to repo
rancher/k3os -> 1898andCo/HAOS
this affects the go packaging as well as pointing
to some artifacts, there are also some documentation
changes to reflect the new package path

diff --git a/overlay/share/rancher/k3os/scripts/k3os-upgrade-kernel b/overlay/share/rancher/k3os/scripts/k3os-upgrade-kernel
--- a/overlay/share/rancher/k3os/scripts/k3os-upgrade-kernel
+++ b/overlay/share/rancher/k3os/scripts/k3os-upgrade-kernel
@@ -2,45 +2,38 @@
 
 set -e
 
-if [ $(whoami) != "root" ]
-then
-	echo "This script must be run as root."
-	exit 1
+if [ $(whoami) != "root" ]; then
+    echo "This script must be run as root."
+    exit 1
 fi
 
 PROC=$(uname -m)
 
 # Take a parameter of the version number (i.e. v0.4.0) if it is given, otherwise use latest
-if [ -z $K3OS_VERSION ]
-then
-	K3OS_VERSION=$(curl -sL api.github.com/repos/rancher/k3os/releases/latest | jq .tag_name -r)
+if [ -z $K3OS_VERSION ]; then
+    K3OS_VERSION=$(curl -sL api.github.com/repos/1898andCo/HAOS/releases/latest | jq .tag_name -r)
 fi
 
-if [ ! -d /k3os/system/kernel ]
-then
-  echo "This system seems to be using a custom kernel, no kernel updates available."
-	exit 1
-elif [ $PROC == "x86_64" ]
-then
-	ARCH="amd64"
-elif [ $PROC == "aarch64" ]
-then
-	ARCH="arm64"
-elif [[ $PROC == arm* ]] # catches armv7l and armhf
-then
-	ARCH="arm"
-	echo "k3os for 32-bit ARM architecture only provides rootfs, no kernel updates available."
-	exit 1
+if [ ! -d /k3os/system/kernel ]; then
+    echo "This system seems to be using a custom kernel, no kernel updates available."
+    exit 1
+elif [ $PROC == "x86_64" ]; then
+    ARCH="amd64"
+elif [ $PROC == "aarch64" ]; then
+    ARCH="arm64"
+elif [[ $PROC == arm* ]]; then # catches armv7l and armhf
+    ARCH="arm"
+    echo "k3os for 32-bit ARM architecture only provides rootfs, no kernel updates available."
+    exit 1
 else
-	echo "Unsupported CPU architecture."
-	exit 1
+    echo "Unsupported CPU architecture."
+    exit 1
 fi
 
-KERNEL_VERSION=$(curl -sL https://github.com/rancher/k3os/releases/download/${K3OS_VERSION}/k3os-kernel-version-${ARCH})
-if [ -z "$KERNEL_VERSION" ]
-then
-  echo "Unable to determine kernel version"
-  exit 1
+KERNEL_VERSION=$(curl -sL https://github.com/1898andCo/HAOS/releases/download/${K3OS_VERSION}/k3os-kernel-version-${ARCH})
+if [ -z "$KERNEL_VERSION" ]; then
+    echo "Unable to determine kernel version"
+    exit 1
 fi
 
 echo "Upgrading k3os kernel to ${KERNEL_VERSION}"
@@ -49,8 +42,8 @@ cd /k3os/system/
 mount -o remount,rw .
 cd kernel
 mkdir -vp ${KERNEL_VERSION}
-curl -sL https://github.com/rancher/k3os/releases/download/${K3OS_VERSION}/k3os-initrd-${ARCH} --output ${KERNEL_VERSION}/initrd
-curl -sL https://github.com/rancher/k3os/releases/download/${K3OS_VERSION}/k3os-kernel-${ARCH}.squashfs --output ${KERNEL_VERSION}/kernel.squashfs
+curl -sL https://github.com/1898andCo/HAOS/releases/download/${K3OS_VERSION}/k3os-initrd-${ARCH} --output ${KERNEL_VERSION}/initrd
+curl -sL https://github.com/1898andCo/HAOS/releases/download/${K3OS_VERSION}/k3os-kernel-${ARCH}.squashfs --output ${KERNEL_VERSION}/kernel.squashfs
 ln -nsf $(readlink current) previous
 ln -nsf ${KERNEL_VERSION} current
 sync
